import { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { journeyMessages } from './journeyMessages'

export type Locale = 'en' | 'id'

type LocaleContextValue = {
  locale: Locale
  setLocale: (locale: Locale) => void
  toggleLocale: () => void
  t: (key: string, values?: Record<string, string | number>) => string
}

const messages: Record<Locale, Record<string, string>> = {
  en: {
    'nav.learn': 'Learn', 'nav.explore': 'Explore', 'nav.playground': 'Playground', 'nav.challenges': 'Challenges', 'nav.cheatSheet': 'Cheat sheet',
    'language.switchTo': 'Switch language to Indonesian', 'language.current': 'English',
    'common.modules': 'modules', 'common.lessons': 'lessons', 'common.complete': 'complete', 'common.min': 'min', 'common.path': 'path',
    'layout.skip': 'Skip to content', 'layout.search': 'Search', 'layout.searchLabel': 'Search (Control or Command K)', 'layout.progressSettings': 'Learning progress settings', 'layout.openMenu': 'Open navigation', 'layout.closeMenu': 'Close navigation',
    'layout.storageBlocked': 'Your browser cannot save progress right now. You can keep learning, but it will last for this session only.', 'layout.loading': 'Opening your learning space…', 'layout.footer': 'Stay curious. Keep making things.', 'layout.progressStays': 'Your progress stays yours', 'layout.source': 'Source', 'layout.mainNavigation': 'Main navigation', 'layout.brandHome': 'UnderCode home', 'layout.trademarkNotice': 'Vercel, the Vercel design, Next.js, and related marks, designs, and logos are trademarks or registered trademarks of Vercel, Inc. and its affiliates in the United States and other countries.', 'dialog.close': 'Close dialog', 'error.loadTitle': 'We couldn’t load this part.', 'error.loadBody': 'Your progress is saved on this device. Reload the page to try again.', 'error.reload': 'Reload page',
    'settings.title': 'Your learning progress', 'settings.lead': 'Your progress stays on this device. No account or cloud sync needed.', 'settings.lessons': 'lessons completed', 'settings.challenges': 'challenges completed', 'settings.resetPrompt': 'Start fresh?', 'settings.resetLead': 'This clears your lesson and challenge progress on this device. Your courses will still be here.', 'settings.reset': 'Reset progress', 'settings.keep': 'Keep my progress', 'settings.resetLocal': 'Reset local progress', 'settings.resetDone': 'Progress cleared. Ready for a fresh start.',
    'search.title': 'What do you want to learn?', 'search.label': 'Search lessons, concepts, challenges and references', 'search.placeholder': 'Search a concept, lesson, or challenge…', 'search.start': 'Start exploring', 'search.results': '{count} result{plural}', 'search.empty': 'No matches for “{query}”', 'search.emptyLead': 'Try “union”, “component”, or a shorter search.', 'search.navigate': 'to navigate', 'search.open': 'to open', 'search.close': 'to close',
    'challenge.choice': 'Choose the answer', 'challenge.fill': 'Fill in the blank', 'challenge.fix': 'Fix the code', 'challenge.editor': 'Challenge code editor', 'challenge.replace': 'Replace the blank with', 'challenge.answer': 'Your answer…', 'challenge.checking': 'Checking types…', 'challenge.check': 'Check answer', 'challenge.hideHint': 'Hide hint', 'challenge.hint': 'Need a hint?', 'challenge.reset': 'Reset challenge', 'challenge.right': 'That’s it.', 'challenge.retry': 'Give it another try.', 'challenge.hideExplanation': 'Hide explanation', 'challenge.showExplanation': 'Show answer & explanation',
    'code.copy': 'Copy code', 'code.editor': 'Code editor', 'code.readOnlyHint': 'Read-only example.', 'code.editHint': 'Tab indents code. Press Escape, then Tab to leave the editor.', 'code.copied': 'Copied', 'code.unavailable': 'Copy unavailable. Select the code to copy.', 'lab.reset': 'Reset', 'lab.preparing': 'Getting the editor ready…', 'lab.tryTitle': 'Try it yourself', 'lab.preview': 'Web preview', 'lab.run': 'Run code', 'lab.running': 'Running…', 'lab.editor': 'Editable TypeScript example', 'lab.inspector': 'Type inspector', 'lab.reading': 'Reading your code…', 'lab.unavailable': 'Analysis unavailable', 'lab.diagnostics': '{count} diagnostic{plural}', 'lab.valid': 'Types check out', 'lab.symbols': 'Select a variable', 'lab.empty': 'Declare a variable or function to inspect its type.', 'lab.errorSuffix': 'You can still read and edit this example.', 'lab.line': 'Line {line}', 'lab.output': 'Console output', 'lab.finished': 'Code finished. Add console.log(...) to see a value.', 'canvas.title': 'Concept canvas', 'canvas.hint': 'Select a node to explore', 'canvas.relationships': 'Relationships', 'canvas.connects': 'connects to', 'stepper.title': 'Step through the example', 'stepper.follow': 'Follow the execution', 'stepper.lead': 'An illustrated trace of this exact example.', 'stepper.line': 'Line {line}', 'stepper.reset': 'Reset', 'stepper.previous': 'Previous', 'stepper.next': 'Next step',
    'reference.allPaths': 'All paths', 'reference.allTopics': 'All topics', 'reference.path': 'Path', 'reference.topic': 'Topic', 'reference.examples': 'examples', 'reference.patterns': 'patterns', 'explore.eyebrow': 'The concept library', 'explore.pageTitle': 'Explore programming concepts', 'explore.heading': 'Connect the dots.', 'explore.lead': 'Start with one idea, see how it works in code, then connect it to the bigger picture. Explore TypeScript, React, and Next.js at your own pace.', 'explore.count': '{count} concepts to explore', 'explore.find': 'Find a concept…', 'explore.concept': 'concept', 'explore.concepts': 'concepts', 'explore.clear': 'Clear search', 'explore.code': 'See it in code', 'explore.mental': 'The mental model', 'explore.practice': 'Put it into practice', 'explore.learn': 'Learn this concept', 'explore.try': 'Try it yourself with a guided explanation and a challenge.', 'explore.open': 'Open lesson', 'explore.missing': 'Concept not found', 'explore.choose': 'Choose a concept from the index to keep exploring.', 'explore.browse': 'Browse concepts',
    'sheet.eyebrow': 'Your desk reference', 'sheet.countLabel': 'Quick reference · all paths', 'sheet.heading': 'A quick reference, right when you need it.', 'sheet.lead': 'TypeScript, React, and Next.js patterns within reach. Find an example, then get back to your code.', 'sheet.placeholder': 'Search syntax, types, or patterns…', 'sheet.searchLabel': 'Search cheat sheet', 'sheet.understand': 'Understand the concept', 'sheet.empty': 'No matching examples', 'sheet.emptyLead': 'Try a shorter search or choose a different path or topic.', 'sheet.reset': 'Reset filters',
    'play.eyebrow': 'A space to experiment', 'play.heading': 'What happens if…', 'play.lead': 'Follow a hunch. Break a type. Make something click.', 'play.cheat': 'Keep the cheat sheet handy', 'play.start': 'Start with an example', 'play.workspace': 'browser workspace', 'play.load': 'Load “{title}”? This replaces your current edits.', 'play.loadButton': 'Load example', 'play.keep': 'Keep editing',
    'challenges.eyebrow': 'Know it. Now try it.', 'challenges.pageTitle': 'Practice challenges', 'challenges.heading': 'Try an idea. See what you understand.', 'challenges.lead': 'Guess what the code will do, find a mistake, or fill in the blank. A little practice helps the ideas sink in.', 'challenges.completed': 'challenges completed', 'challenges.level': 'Level', 'challenges.allLevels': 'All levels', 'challenges.hide': 'Hide completed', 'challenges.choose': 'Choose a challenge', 'challenges.empty': 'No challenges in this view', 'challenges.emptyLead': 'Try another path, topic, or include your completed challenges.', 'challenges.reset': 'Reset filters', 'challenges.saved': 'Your completed challenges are saved in this browser. No account needed.', 'challenges.session': 'Browser storage is unavailable. Progress will last for this session only.',
    'hub.eyebrow': 'UnderCode learning paths', 'hub.heading': 'Learn the stack', 'hub.headingEmphasis': 'as a connected whole.', 'hub.lead': 'Each path has its own destination. Follow the suggested sequence when you are starting out, or open a path directly when you already have the prerequisite.', 'hub.sequence': 'Suggested sequence', 'hub.availablePaths': 'Available learning paths', 'hub.startingPoint': 'Recommended starting point', 'hub.buildsOn': 'Builds on: {prerequisite}', 'hub.startHere': 'Start here', 'hub.viewPath': 'View path', 'hub.continuePath': 'Continue path', 'hub.upNext': 'Up next: {title}',
    'course.headingEmphasis': 'See how the pieces connect.', 'course.curriculum': 'learning path', 'course.aboutHours': 'About {hours} hours, at your pace', 'course.startingPoint': 'Suggested starting point: {prerequisite}. Feel free to explore any lesson.', 'course.progress': 'Your {course} progress', 'course.finished': 'You’ve completed this path. Revisit an idea or keep building.', 'course.upNext': 'Up next: {title}', 'course.beginWith': 'Begin with: {title}', 'course.chooseLesson': 'Choose a lesson below to get started.', 'course.keepPracticing': 'Keep practicing', 'course.continueLearning': 'Continue learning', 'course.startFirst': 'Start the first lesson', 'course.saved': 'Saved on this device. No account needed.', 'course.storageUnavailable': 'Storage is unavailable. Progress lasts for this session.', 'course.roadmap': 'Your roadmap', 'course.roadmapHeading': 'One idea builds on the next.', 'course.roadmapLead': 'Start from the beginning, or jump to a topic you are curious about.', 'course.inProgress': 'In progress', 'course.switchContext': 'Want to switch context?', 'course.browsePaths': 'Browse every learning path',
    'lesson.backToPath': 'Back to {course} path', 'lesson.missing': 'Lesson not found', 'lesson.jump': 'Jump to a lesson', 'lesson.of': 'Lesson {current} of {total}', 'lesson.completed': 'Completed', 'lesson.explain': 'Explain', 'lesson.visualize': 'Visualize', 'lesson.play': 'Play', 'lesson.challenge': 'Challenge', 'lesson.recap': 'Recap', 'lesson.understand': 'Understand', 'lesson.idea': 'The idea', 'lesson.relationship': 'See the relationship', 'lesson.try': 'Try it yourself', 'lesson.change': 'Change the code and see what happens to its type.', 'lesson.editorLead': 'Edit the example and watch the checker respond. Select a symbol to inspect its type, or reset to start again.', 'lesson.playground': 'Keep experimenting in the playground', 'lesson.checkUnderstanding': 'Check your understanding', 'lesson.takeWithYou': 'Take it with you', 'lesson.remember': 'What to remember', 'lesson.done': 'Lesson complete. Your progress is saved on this device.', 'lesson.doneSession': 'Lesson complete for this session. Browser storage is unavailable.', 'lesson.completePrompt': 'Finish the knowledge check to mark this lesson complete. You can open the next lesson whenever you are ready.', 'lesson.exploreFurther': 'Explore this idea further', 'lesson.previous': 'Previous lesson', 'lesson.next': 'Next lesson', 'lesson.backTo': 'Back to', 'lesson.continueStack': 'Continue the stack', 'lesson.paths': 'Learning paths', 'lesson.review': 'Review your learning',
    'home.eyebrow': 'Learn programming by trying things out', 'home.heading': 'Understand how it works.', 'home.headingEmphasis': 'Then build something.', 'home.lead': 'Understand why the code works. Follow a type, component, or route until the idea makes sense.', 'home.explorePaths': 'Explore learning paths', 'home.free': 'Free to explore. No account needed.', 'home.change': 'A little change. A new understanding.', 'home.tryBelow': 'Try it below', 'home.resume': 'Pick up where you left off', 'home.lessonsComplete': '{completed}/{total} lessons complete', 'home.stack': 'From first steps to full apps', 'home.fromTypes': 'From types,', 'home.toApps': 'to apps.', 'home.stackLead': 'Start with TypeScript, turn your ideas into interfaces with React, then bring everything together with Next.js.', 'home.everyPath': 'Explore every learning path', 'home.focusedLessons': 'focused lessons', 'home.connectedPaths': 'connected paths', 'home.browseConcepts': 'Browse concepts across the stack', 'home.rhythm': 'A rhythm for understanding', 'home.seeIdea': 'See the idea', 'home.seeIdeaBody': 'A short explanation and a visual mental model.', 'home.changeTitle': 'Make a change', 'home.changeBody': 'Experiment with real code and follow what happens.', 'home.ownTitle': 'Make it yours', 'home.ownBody': 'Check your understanding before moving forward.',
  },
  id: {
    'nav.learn': 'Belajar', 'nav.explore': 'Jelajahi', 'nav.playground': 'Lab Kode', 'nav.challenges': 'Tantangan', 'nav.cheatSheet': 'Ringkasan Kode',
    'language.switchTo': 'Ganti bahasa ke English', 'language.current': 'Bahasa Indonesia',
    'common.modules': 'modul', 'common.lessons': 'pelajaran', 'common.complete': 'selesai', 'common.min': 'mnt', 'common.path': 'jalur',
    'layout.skip': 'Lewati ke konten', 'layout.search': 'Cari', 'layout.searchLabel': 'Cari (Control atau Command K)', 'layout.progressSettings': 'Pengaturan progres belajar', 'layout.openMenu': 'Buka navigasi', 'layout.closeMenu': 'Tutup navigasi',
    'layout.storageBlocked': 'Browser-mu belum bisa menyimpan progres. Kamu tetap bisa belajar, tapi progres hanya berlaku selama sesi ini.', 'layout.loading': 'Membuka ruang belajarmu…', 'layout.footer': 'Terus penasaran, terus bikin sesuatu.', 'layout.progressStays': 'Progresmu tetap milikmu', 'layout.source': 'Sumber', 'layout.mainNavigation': 'Navigasi utama', 'layout.brandHome': 'Beranda UnderCode', 'layout.trademarkNotice': 'Vercel, desain Vercel, Next.js, serta merek, desain, dan logo terkait adalah merek dagang atau merek dagang terdaftar milik Vercel, Inc. dan afiliasinya di Amerika Serikat maupun negara lain.', 'dialog.close': 'Tutup dialog', 'error.loadTitle': 'Bagian ini gagal dimuat.', 'error.loadBody': 'Progresmu tersimpan di perangkat ini. Muat ulang halaman untuk mencoba lagi.', 'error.reload': 'Muat ulang halaman',
    'settings.title': 'Progres belajarmu', 'settings.lead': 'Progresmu tersimpan di perangkat ini. Kamu tidak perlu akun atau sinkronisasi cloud.', 'settings.lessons': 'pelajaran selesai', 'settings.challenges': 'tantangan selesai', 'settings.resetPrompt': 'Mulai lagi dari awal?', 'settings.resetLead': 'Ini akan menghapus progres pelajaran dan tantangan di perangkat ini. Semua materi tetap tersedia.', 'settings.reset': 'Reset progres', 'settings.keep': 'Simpan progresku', 'settings.resetLocal': 'Reset progres lokal', 'settings.resetDone': 'Progres dihapus. Siap mulai lagi.',
    'search.title': 'Mau belajar apa?', 'search.label': 'Cari pelajaran, konsep, tantangan, dan referensi', 'search.placeholder': 'Cari konsep, pelajaran, atau tantangan…', 'search.start': 'Mulai menjelajah', 'search.results': '{count} hasil', 'search.empty': 'Tidak ada hasil untuk “{query}”', 'search.emptyLead': 'Coba “union”, “component”, atau kata pencarian yang lebih singkat.', 'search.navigate': 'untuk navigasi', 'search.open': 'untuk membuka', 'search.close': 'untuk menutup',
    'challenge.choice': 'Pilih jawaban', 'challenge.fill': 'Isi bagian kosong', 'challenge.fix': 'Perbaiki kode', 'challenge.editor': 'Editor kode tantangan', 'challenge.replace': 'Ganti bagian kosong dengan', 'challenge.answer': 'Jawabanmu…', 'challenge.checking': 'Memeriksa tipe…', 'challenge.check': 'Periksa jawaban', 'challenge.hideHint': 'Sembunyikan petunjuk', 'challenge.hint': 'Butuh petunjuk?', 'challenge.reset': 'Reset tantangan', 'challenge.right': 'Betul, kamu sudah paham.', 'challenge.retry': 'Coba sekali lagi.', 'challenge.hideExplanation': 'Sembunyikan penjelasan', 'challenge.showExplanation': 'Tampilkan jawaban & penjelasan',
    'code.copy': 'Salin kode', 'code.editor': 'Editor kode', 'code.readOnlyHint': 'Contoh kode ini hanya untuk dibaca.', 'code.editHint': 'Tab untuk membuat indentasi. Tekan Escape, lalu Tab untuk keluar dari editor.', 'code.copied': 'Tersalin', 'code.unavailable': 'Salin tidak tersedia. Pilih kode untuk menyalinnya.', 'lab.reset': 'Reset', 'lab.preparing': 'Menyiapkan editor…', 'lab.tryTitle': 'Coba sendiri', 'lab.preview': 'Pratinjau halaman web', 'lab.run': 'Jalankan kode', 'lab.running': 'Menjalankan…', 'lab.editor': 'Contoh TypeScript yang dapat diedit', 'lab.inspector': 'Pemeriksa tipe', 'lab.reading': 'Membaca kodemu…', 'lab.unavailable': 'Analisis tidak tersedia', 'lab.diagnostics': '{count} diagnostik', 'lab.valid': 'Tipe sudah sesuai', 'lab.symbols': 'Pilih sebuah variabel', 'lab.empty': 'Buat variabel atau function untuk memeriksa tipenya.', 'lab.errorSuffix': 'Contoh ini tetap dapat kamu baca dan edit.', 'lab.line': 'Baris {line}', 'lab.output': 'Output console', 'lab.finished': 'Kode selesai. Tambahkan console.log(...) untuk melihat nilainya.', 'canvas.title': 'Kanvas konsep', 'canvas.hint': 'Pilih node untuk menjelajah', 'canvas.relationships': 'Hubungan', 'canvas.connects': 'terhubung ke', 'stepper.title': 'Ikuti contoh ini langkah demi langkah', 'stepper.follow': 'Ikuti prosesnya', 'stepper.lead': 'Penelusuran visual dari contoh ini.', 'stepper.line': 'Baris {line}', 'stepper.reset': 'Reset', 'stepper.previous': 'Sebelumnya', 'stepper.next': 'Langkah berikutnya',
    'reference.allPaths': 'Semua jalur', 'reference.allTopics': 'Semua topik', 'reference.path': 'Jalur', 'reference.topic': 'Topik', 'reference.examples': 'contoh', 'reference.patterns': 'pola', 'explore.eyebrow': 'Kumpulan konsep coding', 'explore.pageTitle': 'Jelajahi konsep coding', 'explore.heading': 'Hubungkan setiap titik.', 'explore.lead': 'Mulai dari satu konsep, lihat cara kerjanya lewat kode, lalu pahami kaitannya dengan hal lain. Pelajari TypeScript, React, dan Next.js sesuai ritmemu.', 'explore.count': '{count} konsep untuk dijelajahi', 'explore.find': 'Cari konsep…', 'explore.concept': 'konsep', 'explore.concepts': 'konsep', 'explore.clear': 'Hapus pencarian', 'explore.code': 'Lihat di dalam kode', 'explore.mental': 'Model mentalnya', 'explore.practice': 'Terapkan langsung', 'explore.learn': 'Pelajari konsep ini', 'explore.try': 'Coba sendiri melalui penjelasan dan tantangan terpandu.', 'explore.open': 'Buka pelajaran', 'explore.missing': 'Konsep tidak ditemukan', 'explore.choose': 'Pilih konsep dari daftar untuk lanjut menjelajah.', 'explore.browse': 'Jelajahi konsep',
    'sheet.eyebrow': 'Referensi cepatmu', 'sheet.countLabel': 'Ringkasan cepat · semua jalur', 'sheet.heading': 'Cari contoh, lalu lanjut bikin.', 'sheet.lead': 'Pola TypeScript, React, dan Next.js selalu dekat. Temukan contoh, lalu kembali ke kodemu.', 'sheet.placeholder': 'Cari sintaks, types, atau pola…', 'sheet.searchLabel': 'Cari ringkasan kode', 'sheet.understand': 'Pahami konsepnya', 'sheet.empty': 'Tidak ada contoh yang sesuai', 'sheet.emptyLead': 'Coba pencarian yang lebih pendek atau pilih jalur maupun topik lain.', 'sheet.reset': 'Reset filter',
    'play.eyebrow': 'Ruang untuk bereksperimen', 'play.heading': 'Apa yang terjadi jika…', 'play.lead': 'Ikuti dugaanmu. Ubah sebuah type. Buat konsepnya terasa masuk akal.', 'play.cheat': 'Buka ringkasan kode', 'play.start': 'Mulai dari contoh', 'play.workspace': 'ruang kerja browser', 'play.load': 'Muat “{title}”? Tindakan ini mengganti perubahanmu saat ini.', 'play.loadButton': 'Muat contoh', 'play.keep': 'Tetap mengedit',
    'challenges.eyebrow': 'Sudah paham? Coba langsung.', 'challenges.pageTitle': 'Tantangan coding', 'challenges.heading': 'Coba dulu, pahami lewat praktik.', 'challenges.lead': 'Tebak apa yang akan dilakukan kodenya, cari kesalahannya, atau lengkapi bagian yang kosong. Latihan kecil bisa bantu kamu makin paham.', 'challenges.completed': 'tantangan selesai', 'challenges.level': 'Level', 'challenges.allLevels': 'Semua level', 'challenges.hide': 'Sembunyikan yang selesai', 'challenges.choose': 'Pilih tantangan', 'challenges.empty': 'Tidak ada tantangan pada tampilan ini', 'challenges.emptyLead': 'Coba jalur, topik lain, atau tampilkan kembali tantangan yang selesai.', 'challenges.reset': 'Reset filter', 'challenges.saved': 'Tantangan selesai tersimpan di browser ini. Tidak perlu akun.', 'challenges.session': 'Penyimpanan browser tidak tersedia. Progres hanya berlangsung selama sesi ini.',
    'hub.eyebrow': 'Jalur belajar UnderCode', 'hub.heading': 'Pelajari seluruh stack', 'hub.headingEmphasis': 'sebagai satu kesatuan.', 'hub.lead': 'Setiap jalur punya tujuan sendiri. Ikuti urutan yang disarankan saat baru mulai, atau langsung buka jalur yang prasyaratnya sudah kamu kuasai.', 'hub.sequence': 'Urutan yang disarankan', 'hub.availablePaths': 'Jalur belajar yang tersedia', 'hub.startingPoint': 'Titik awal yang disarankan', 'hub.buildsOn': 'Berdasarkan: {prerequisite}', 'hub.startHere': 'Mulai di sini', 'hub.viewPath': 'Lihat jalur', 'hub.continuePath': 'Lanjutkan jalur', 'hub.upNext': 'Berikutnya: {title}',
    'course.headingEmphasis': 'Lihat bagaimana semuanya terhubung.', 'course.curriculum': 'jalur belajar', 'course.aboutHours': 'Sekitar {hours} jam, sesuai ritmemu', 'course.startingPoint': 'Sebaiknya mulai dari {prerequisite}. Kamu tetap bebas membuka pelajaran mana pun.', 'course.progress': 'Progres {course} kamu', 'course.finished': 'Kamu sudah menyelesaikan jalur ini. Ulangi ide penting atau lanjut membangun.', 'course.upNext': 'Berikutnya: {title}', 'course.beginWith': 'Mulai dari: {title}', 'course.chooseLesson': 'Pilih pelajaran di bawah untuk mulai belajar.', 'course.keepPracticing': 'Terus berlatih', 'course.continueLearning': 'Lanjut belajar', 'course.startFirst': 'Mulai pelajaran pertama', 'course.saved': 'Tersimpan di perangkat ini. Tidak perlu akun.', 'course.storageUnavailable': 'Penyimpanan tidak tersedia. Progres berlaku selama sesi ini.', 'course.roadmap': 'Peta belajarmu', 'course.roadmapHeading': 'Satu ide membangun ide berikutnya.', 'course.roadmapLead': 'Mulai dari awal, atau langsung buka topik yang membuatmu penasaran.', 'course.inProgress': 'Sedang dipelajari', 'course.switchContext': 'Ingin ganti konteks?', 'course.browsePaths': 'Lihat semua jalur belajar',
    'lesson.backToPath': 'Kembali ke jalur {course}', 'lesson.missing': 'Pelajaran tidak ditemukan', 'lesson.jump': 'Pindah ke pelajaran', 'lesson.of': 'Pelajaran {current} dari {total}', 'lesson.completed': 'Selesai', 'lesson.explain': 'Pahami', 'lesson.visualize': 'Visualisasikan', 'lesson.play': 'Coba', 'lesson.challenge': 'Tantangan', 'lesson.recap': 'Rangkuman', 'lesson.understand': 'Pahami', 'lesson.idea': 'Inti idenya', 'lesson.relationship': 'Lihat hubungannya', 'lesson.try': 'Coba sendiri', 'lesson.change': 'Ubah kodenya, lalu lihat bagaimana type-nya berubah.', 'lesson.editorLead': 'Ubah contoh ini dan lihat respons pemeriksa tipe. Pilih simbol untuk melihat tipenya, atau reset untuk memulai lagi.', 'lesson.playground': 'Lanjut bereksperimen di playground', 'lesson.checkUnderstanding': 'Uji pemahamanmu', 'lesson.takeWithYou': 'Bawa ke praktik', 'lesson.remember': 'Yang perlu diingat', 'lesson.done': 'Pelajaran selesai. Progresmu tersimpan di perangkat ini.', 'lesson.doneSession': 'Pelajaran selesai untuk sesi ini. Penyimpanan browser tidak tersedia.', 'lesson.completePrompt': 'Selesaikan cek pemahaman untuk menandai pelajaran ini selesai. Buka pelajaran berikutnya kapan pun kamu siap.', 'lesson.exploreFurther': 'Jelajahi ide ini lebih dalam', 'lesson.previous': 'Pelajaran sebelumnya', 'lesson.next': 'Pelajaran berikutnya', 'lesson.backTo': 'Kembali ke', 'lesson.continueStack': 'Lanjut ke stack berikutnya', 'lesson.paths': 'Jalur belajar', 'lesson.review': 'Tinjau belajarmu',
    'home.eyebrow': 'Belajar coding dengan langsung mencoba', 'home.heading': 'Pahami cara kerjanya.', 'home.headingEmphasis': 'Lalu mulai bikin.', 'home.lead': 'Cari tahu kenapa kode itu bekerja. Ikuti type, komponen, atau route sampai semuanya terasa masuk akal.', 'home.explorePaths': 'Jelajahi jalur belajar', 'home.free': 'Bebas dijelajahi. Tidak perlu akun.', 'home.change': 'Sedikit perubahan. Pemahaman baru.', 'home.tryBelow': 'Coba di bawah ini', 'home.resume': 'Lanjutkan dari bagian terakhir', 'home.lessonsComplete': '{completed}/{total} pelajaran selesai', 'home.stack': 'Dari dasar sampai bikin aplikasi', 'home.fromTypes': 'Dari types,', 'home.toApps': 'ke aplikasi.', 'home.stackLead': 'Mulai dengan TypeScript, wujudkan idemu menjadi antarmuka di React, lalu rangkai semuanya dengan Next.js.', 'home.everyPath': 'Jelajahi semua jalur belajar', 'home.focusedLessons': 'pelajaran terarah', 'home.connectedPaths': 'jalur yang terhubung', 'home.browseConcepts': 'Jelajahi konsep di seluruh stack', 'home.rhythm': 'Ritme untuk memahami', 'home.seeIdea': 'Lihat idenya', 'home.seeIdeaBody': 'Penjelasan singkat dan model mental visual.', 'home.changeTitle': 'Buat perubahan', 'home.changeBody': 'Bereksperimen dengan kode nyata dan ikuti yang terjadi.', 'home.ownTitle': 'Jadikan milikmu', 'home.ownBody': 'Uji pemahamanmu sebelum melanjutkan.',
  },
}

const LocaleContext = createContext<LocaleContextValue | null>(null)
const storageKey = 'undercode-locale'

function interpolate(message: string, values?: Record<string, string | number>) {
  return message.replace(/\{(\w+)\}/g, (_, key) => String(values?.[key] ?? `{${key}}`))
}

export function LocaleProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => { try { return localStorage.getItem(storageKey) === 'id' ? 'id' : 'en' } catch { return 'en' } })

  useEffect(() => {
    try { localStorage.setItem(storageKey, locale) } catch { /* The interface remains usable when storage is unavailable. */ }
    document.documentElement.lang = locale
  }, [locale])

  const value = useMemo<LocaleContextValue>(() => ({
    locale,
    setLocale,
    toggleLocale: () => setLocale(current => current === 'en' ? 'id' : 'en'),
    t: (key, values) => interpolate(journeyMessages[locale][key] ?? messages[locale][key] ?? messages.en[key] ?? key, values),
  }), [locale])

  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>
}

export function useLocale() {
  const context = useContext(LocaleContext)
  if (!context) throw new Error('useLocale must be used within LocaleProvider')
  return context
}
