import type { Challenge, Concept, CourseModule, Lesson } from './types'
import { flow, node } from './visuals'

type Seed = { id: string; title: string; moduleId: string; minutes: number; description: string; code: string; symbols: string[]; topic: string; question: string; answer: string; options: string[]; recap: string[] }

function graph(title: string, input: string, output: string) {
  return flow(title, 'Follow the information through the pattern. Select a node to read its role.', [
    node('input', input, 'A value enters this part of the pattern.', 'value'),
    node('logic', title, 'This focused piece decides how to use that value.'),
    node('output', output, 'A new value or view is ready for the next step.', 'type'),
  ], [{ from: 'input', to: 'logic', label: 'passes data' }, { from: 'logic', to: 'output', label: 'returns' }])
}

function makeLessons(courseId: string, seeds: Seed[]): Lesson[] {
  return seeds.map((seed) => {
    const challenge: Challenge = { id: `${seed.id}-check`, title: `Check: ${seed.title}`, topic: seed.topic, difficulty: 'Beginner', kind: 'choice', prompt: seed.question, code: seed.code, options: seed.options, answer: seed.answer, hint: 'Look at the boundary between input, logic, and result.', explanation: `${seed.answer} follows the pattern shown in this lesson.` }
    const comparison = courseId === 'react'
      ? { beforeLabel: 'The model', before: seed.code, afterLabel: 'In a React component', after: `type Props = { title: string };\n\nexport function Example({ title }: Props) {\n  return <section>\n    <h2>{title}</h2>\n  </section>;\n}` }
      : { beforeLabel: 'The model', before: seed.code, afterLabel: 'In a Next.js route', after: `export default async function Page() {\n  const title = "${seed.title}";\n\n  return <main>\n    <h1>{title}</h1>\n  </main>;\n}` }
    return { id: seed.id, courseId, title: seed.title, moduleId: seed.moduleId, minutes: seed.minutes, description: seed.description, explanation: [seed.description, 'The editable example focuses on the underlying JavaScript and TypeScript model. The comparison shows the same idea in its React or Next.js home.'], code: seed.code, inspectSymbols: seed.symbols, visual: graph(seed.title, seed.symbols[0] ?? 'input', seed.symbols.at(-1) ?? 'result'), challenge, recap: seed.recap, relatedConcepts: [`${courseId}-${seed.id}`], comparison }
  })
}

const reactSeeds: Seed[] = [
  { id: 'react-components', title: 'Thinking in Components', moduleId: 'react-foundations', minutes: 7, description: 'A component is a focused function that turns inputs into one meaningful part of an interface. Find product boundaries before splitting markup.', code: 'type Profile = { name: string; role: string };\n\nfunction profileLabel(profile: Profile): string {\n  return `${profile.name} · ${profile.role}`;\n}\n\nconst label = profileLabel({ name: "Ada", role: "Engineer" });\nconsole.log(label);', symbols: ['Profile', 'profileLabel', 'label'], topic: 'React foundations', question: 'What should a well-scoped component represent?', answer: 'One meaningful piece of the interface', options: ['One meaningful piece of the interface', 'Every HTML element', 'An entire app in one file'], recap: ['Components describe focused pieces of UI.', 'They receive data and return a view.', 'Choose boundaries based on meaning and reuse.'] },
  { id: 'react-jsx-props', title: 'JSX and Props', moduleId: 'react-foundations', minutes: 7, description: 'JSX describes a UI tree, while props let a parent provide the values a child needs. Curly braces bring JavaScript expressions into JSX.', code: 'type LessonCardProps = { title: string; minutes: number };\n\nfunction summary({ title, minutes }: LessonCardProps) {\n  return `${title} · ${minutes} min`;\n}\n\nconst text = summary({ title: "Props", minutes: 7 });', symbols: ['LessonCardProps', 'summary', 'text'], topic: 'React foundations', question: 'Who provides a component’s props?', answer: 'Its parent', options: ['Its parent', 'The browser automatically', 'Only the component itself'], recap: ['JSX describes a UI tree.', 'Props are read-only inputs from a parent.', 'A props type documents a component contract.'] },
  { id: 'react-state-events', title: 'State and Events', moduleId: 'react-state', minutes: 8, description: 'State is a component’s changing memory. Events decide the next state from the current state, then React updates the view from that new value.', code: 'type Counter = { count: number };\n\nfunction increment(counter: Counter): Counter {\n  return { count: counter.count + 1 };\n}\n\nconst next = increment({ count: 2 });\nconsole.log(next.count);', symbols: ['Counter', 'increment', 'next'], topic: 'React state', question: 'What should you do with a state object?', answer: 'Create the next value instead of mutating it', options: ['Create the next value instead of mutating it', 'Change it directly anywhere', 'Store every value globally'], recap: ['State holds values that can change.', 'Events calculate the next state.', 'Do not mutate existing state objects.'] },
  { id: 'react-lists-keys', title: 'Lists and Keys', moduleId: 'react-state', minutes: 7, description: 'A list maps data to repeated UI. A stable key lets React recognize the same item when the list changes.', code: 'type Todo = { id: string; title: string };\nconst todos: Todo[] = [{ id: "learn", title: "Learn keys" }, { id: "build", title: "Build a list" }];\nconst labels = todos.map((todo) => `${todo.id}: ${todo.title}`);\nconsole.log(labels);', symbols: ['Todo', 'todos', 'labels'], topic: 'React state', question: 'What makes a good key for a list item?', answer: 'A stable ID from the data', options: ['A stable ID from the data', 'A new random value each render', 'Always the array index'], recap: ['Map data to repeated UI.', 'Keys identify siblings between renders.', 'Use stable IDs when order can change.'] },
  { id: 'react-effects', title: 'Effects and External Systems', moduleId: 'react-effects', minutes: 8, description: 'Effects synchronize a component with something outside React, such as a browser API, timer, subscription, or request. Ordinary derived values belong in render.', code: 'type Connection = { active: boolean };\n\nfunction connect(): Connection {\n  return { active: true };\n}\n\nconst connection = connect();\nconsole.log(connection.active);', symbols: ['Connection', 'connect', 'connection'], topic: 'React effects', question: 'What is an effect for?', answer: 'Synchronizing with an external system', options: ['Synchronizing with an external system', 'Calculating every value in render', 'Replacing all event handlers'], recap: ['Effects connect React to external systems.', 'Derived values usually belong in render.', 'Clean up subscriptions and timers.'] },
  { id: 'react-composition-hooks', title: 'Composition and Custom Hooks', moduleId: 'react-effects', minutes: 8, description: 'Composition gives one component structure while another provides content. A custom Hook packages reusable stateful logic without sharing component state.', code: 'type Toggle = { on: boolean };\n\nfunction toggle(value: Toggle): Toggle {\n  return { on: !value.on };\n}\n\nconst nextToggle = toggle({ on: false });\nconsole.log(nextToggle.on);', symbols: ['Toggle', 'toggle', 'nextToggle'], topic: 'React effects', question: 'What does a custom Hook reuse?', answer: 'Stateful logic', options: ['Stateful logic', 'One shared component instance', 'A global CSS file'], recap: ['Composition combines focused pieces.', 'Custom Hooks package stateful logic.', 'Each use receives its own state.'] },
]

const nextSeeds: Seed[] = [
  { id: 'next-file-routing', title: 'File-based Routing', moduleId: 'next-routing', minutes: 7, description: 'In the App Router, folders and special files describe routes. A page file is the UI entry point for one URL segment.', code: 'const segments = ["learn", "react"];\nconst path = `/${segments.join("/")}`;\nconsole.log(path);', symbols: ['segments', 'path'], topic: 'Next.js routing', question: 'Which file defines UI for a route in the App Router?', answer: 'page.tsx', options: ['page.tsx', 'route.ts', 'next.config.ts'], recap: ['Folders describe URL segments.', 'page.tsx renders a route.', 'Keep route UI close to its route.'] },
  { id: 'next-layouts-dynamic', title: 'Layouts and Dynamic Segments', moduleId: 'next-routing', minutes: 8, description: 'Layouts provide shared structure for related routes. A bracketed folder captures a URL value so a route can find the resource it needs.', code: 'type Params = { slug: string };\nfunction lessonPath({ slug }: Params) { return `/learn/${slug}`; }\nconst url = lessonPath({ slug: "react-state" });', symbols: ['Params', 'lessonPath', 'url'], topic: 'Next.js routing', question: 'What does [slug] represent in a route folder?', answer: 'A value captured from the URL', options: ['A value captured from the URL', 'A CSS class', 'A server secret'], recap: ['Layouts wrap related child routes.', 'Dynamic segments capture URL values.', 'Validate missing or invalid data.'] },
  { id: 'next-server-components', title: 'Server Components', moduleId: 'next-rendering', minutes: 8, description: 'Server Components render on the server by default. They can fetch data close to the component without shipping their implementation to the browser.', code: 'type Lesson = { title: string };\nasync function getLesson(): Promise<Lesson> { return { title: "Server Components" }; }\nconst lesson = await getLesson();\nconsole.log(lesson.title);', symbols: ['Lesson', 'getLesson', 'lesson'], topic: 'Next.js rendering', question: 'Where do Server Components render by default?', answer: 'On the server', options: ['On the server', 'Only in a browser event handler', 'Inside CSS'], recap: ['App Router components are server components by default.', 'They can await data directly.', 'Their code is not automatically sent to the browser.'] },
  { id: 'next-client-components', title: 'Client Components', moduleId: 'next-rendering', minutes: 8, description: 'Use "use client" at the boundary that needs browser state, effects, or event handlers. Keep that boundary small so the browser receives only what it needs.', code: 'type Menu = { open: boolean };\nfunction toggleMenu(menu: Menu): Menu { return { open: !menu.open }; }\nconst nextMenu = toggleMenu({ open: false });\nconsole.log(nextMenu.open);', symbols: ['Menu', 'toggleMenu', 'nextMenu'], topic: 'Next.js rendering', question: 'When is "use client" needed?', answer: 'When a component needs browser interactivity', options: ['When a component needs browser interactivity', 'For every page', 'To fetch all data'], recap: ['Client Components enable browser APIs and state.', 'The directive creates a client boundary.', 'Keep client boundaries narrow.'] },
  { id: 'next-data-fetching', title: 'Data Fetching and States', moduleId: 'next-experience', minutes: 8, description: 'Fetch data where it is needed, then deliberately design loading, success, empty, and error states. Request data has a lifecycle, not only a final value.', code: 'type Result = { title: string };\nasync function fetchLesson(): Promise<Result> { return { title: "Data Fetching" }; }\nconst result = await fetchLesson();\nconsole.log(result.title);', symbols: ['Result', 'fetchLesson', 'result'], topic: 'Next.js experience', question: 'What should a data-driven route plan for?', answer: 'Loading, success, empty, and error states', options: ['Loading, success, empty, and error states', 'Only the happy path', 'A global mutable variable'], recap: ['Fetch data close to its consumer.', 'Plan for each request state.', 'Keep data shape explicit.'] },
  { id: 'next-metadata-route-handlers', title: 'Metadata and Route Handlers', moduleId: 'next-experience', minutes: 8, description: 'Metadata describes a route for people and browsers. Route Handlers create server endpoints that should validate input and return clear responses.', code: 'type Input = { name: string };\ntype Output = { greeting: string };\nfunction greet(input: Input): Output { return { greeting: `Hello, ${input.name}` }; }\nconsole.log(greet({ name: "Mira" }).greeting);', symbols: ['Input', 'Output', 'greet'], topic: 'Next.js experience', question: 'Where should sensitive Route Handler work run?', answer: 'On the server', options: ['On the server', 'In a public browser variable', 'Inside CSS'], recap: ['Metadata belongs with the route it describes.', 'Route Handlers create HTTP endpoints.', 'Validate data at the server boundary.'] },
]

type ExpansionSeed = Omit<Seed, 'minutes' | 'options'> & { minutes?: number }

function expandSeed(seed: ExpansionSeed): Seed {
  return {
    ...seed,
    minutes: seed.minutes ?? 7,
    options: [seed.answer, 'A value that happens outside this component', 'A browser setting chosen at random'],
  }
}

const reactExpansionSeeds: Seed[] = [
  expandSeed({ id: 'react-conditional-rendering', title: 'Conditional Rendering', moduleId: 'react-foundations', description: 'Use ordinary JavaScript conditions to choose the UI that matches the current data. Keep each branch meaningful enough to read on its own.', code: 'type Session = { signedIn: boolean };\n\nfunction screen(session: Session) {\n  return session.signedIn ? "Dashboard" : "Sign in";\n}\n\nconst view = screen({ signedIn: true });', symbols: ['Session', 'screen', 'view'], topic: 'React foundations', question: 'What should decide which UI branch React renders?', answer: 'The current data and state', recap: ['Conditions select the appropriate view.', 'Keep branches readable.', 'Do not use effects to derive conditional UI.'] }),
  expandSeed({ id: 'react-component-boundaries', title: 'Choosing Component Boundaries', moduleId: 'react-foundations', description: 'Split a component when a part has its own responsibility, state, or reuse value. The goal is a map of clear ideas, not the smallest possible files.', code: 'type Section = { heading: string; body: string };\n\nfunction sectionSummary(section: Section) {\n  return `${section.heading}: ${section.body}`;\n}\n\nconst summary = sectionSummary({ heading: "Profile", body: "Account details" });', symbols: ['Section', 'sectionSummary', 'summary'], topic: 'React foundations', question: 'When is a separate component useful?', answer: 'When a part has a clear responsibility or reuse value', recap: ['Components should have a clear job.', 'Split by meaning, not by arbitrary markup depth.', 'Keep closely related code together.'] }),
  expandSeed({ id: 'react-styling-ui', title: 'Styling a Component', moduleId: 'react-foundations', description: 'Styles should reinforce component states and hierarchy. Build class names from meaningful variants instead of tying style decisions to fragile DOM structure.', code: 'type Tone = "quiet" | "highlight";\n\nfunction cardClass(tone: Tone) {\n  return `card card--${tone}`;\n}\n\nconst className = cardClass("highlight");', symbols: ['Tone', 'cardClass', 'className'], topic: 'React foundations', question: 'What should a styling variant describe?', answer: 'A meaningful visual state or role', recap: ['Use names that describe purpose.', 'Keep visual states explicit.', 'Let component structure guide styling boundaries.'] }),
  expandSeed({ id: 'react-updating-objects', title: 'Updating Objects in State', moduleId: 'react-state', description: 'State updates replace the old value with a new one. Copy the object and change only the field that the event is responsible for.', code: 'type Profile = { name: string; subscribed: boolean };\n\nfunction subscribe(profile: Profile): Profile {\n  return { ...profile, subscribed: true };\n}\n\nconst next = subscribe({ name: "Ari", subscribed: false });', symbols: ['Profile', 'subscribe', 'next'], topic: 'React state', question: 'How should an object state update be written?', answer: 'Create a new object with the changed field', recap: ['Treat state as immutable.', 'Copy before changing a field.', 'Each event should make one clear transition.'] }),
  expandSeed({ id: 'react-updating-arrays', title: 'Updating Arrays in State', moduleId: 'react-state', description: 'Array operations such as map, filter, and spread create a new collection. They make adding, changing, and removing items predictable.', code: 'type Task = { id: string; done: boolean };\n\nfunction finish(tasks: Task[], id: string) {\n  return tasks.map(task => task.id === id ? { ...task, done: true } : task);\n}\n\nconst tasks = finish([{ id: "read", done: false }], "read");', symbols: ['Task', 'finish', 'tasks'], topic: 'React state', question: 'Which array method is useful for changing one item?', answer: 'map', recap: ['Map changes matching items.', 'Filter removes items.', 'New arrays preserve React state updates.'] }),
  expandSeed({ id: 'react-controlled-inputs', title: 'Controlled Inputs', moduleId: 'react-state', description: 'A controlled input displays a value from state and reports changes through an event. This gives the UI one dependable source of truth.', code: 'type Form = { email: string };\n\nfunction changeEmail(form: Form, email: string): Form {\n  return { ...form, email };\n}\n\nconst draft = changeEmail({ email: "" }, "hi@underco.de");', symbols: ['Form', 'changeEmail', 'draft'], topic: 'React state', question: 'Where does a controlled input get its displayed value?', answer: 'From component state', recap: ['State owns the displayed value.', 'Events create the next value.', 'Controlled inputs make validation easier.'] }),
  expandSeed({ id: 'react-refs', title: 'Refs and DOM Values', moduleId: 'react-effects', description: 'A ref stores a value that React does not need to render, such as a DOM node, timer ID, or previous value. Updating it does not trigger a render.', code: 'type Ref<T> = { current: T };\n\nconst focusTarget: Ref<string | null> = { current: null };\nfocusTarget.current = "search-input";\nconsole.log(focusTarget.current);', symbols: ['Ref', 'focusTarget'], topic: 'React effects', question: 'When is a ref appropriate?', answer: 'For a value that does not affect rendering', recap: ['Refs persist between renders.', 'Changing a ref does not re-render.', 'Use refs for DOM and imperative integrations.'] }),
  expandSeed({ id: 'react-effect-dependencies', title: 'Effect Dependencies', moduleId: 'react-effects', description: 'An effect must declare every reactive value it reads. The dependency list communicates when React needs to synchronize the external system again.', code: 'type Query = { term: string };\n\nfunction requestKey(query: Query) {\n  return `search:${query.term}`;\n}\n\nconst key = requestKey({ term: "hooks" });', symbols: ['Query', 'requestKey', 'key'], topic: 'React effects', question: 'What belongs in an effect dependency list?', answer: 'Every reactive value read by the effect', recap: ['Dependencies describe synchronization inputs.', 'Do not omit values to silence a rerun.', 'Move non-reactive work outside the effect when possible.'] }),
  expandSeed({ id: 'react-effect-cleanup', title: 'Cleaning Up Effects', moduleId: 'react-effects', description: 'Subscriptions, timers, and listeners need a cleanup function so an old connection cannot keep running after the component changes or leaves the page.', code: 'type Timer = { active: boolean };\n\nfunction stop(timer: Timer): Timer {\n  return { active: false };\n}\n\nconst cleared = stop({ active: true });', symbols: ['Timer', 'stop', 'cleared'], topic: 'React effects', question: 'When does React run an effect cleanup?', answer: 'Before re-synchronizing and when the component unmounts', recap: ['Clean up external resources.', 'Avoid duplicate subscriptions.', 'Match setup and cleanup responsibilities.'] }),
  expandSeed({ id: 'react-lifting-state', title: 'Lifting State Up', moduleId: 'react-composition', description: 'When two components must agree on a value, move that state to their closest shared parent. Pass the value and event callbacks down as props.', code: 'type Selection = { activeId: string };\n\nfunction select(_: Selection, activeId: string): Selection {\n  return { activeId };\n}\n\nconst state = select({ activeId: "one" }, "two");', symbols: ['Selection', 'select', 'state'], topic: 'React composition', question: 'Where should shared state live?', answer: 'In the closest common parent', recap: ['One owner keeps shared UI in sync.', 'Children receive values through props.', 'Children report intent through callbacks.'] }),
  expandSeed({ id: 'react-context', title: 'Context Without Prop Drilling', moduleId: 'react-composition', description: 'Context makes a stable value available to a distant subtree. It works best for broadly needed concerns such as theme, locale, or authenticated user information.', code: 'type Theme = "light" | "dark";\n\nfunction label(theme: Theme) {\n  return `Theme: ${theme}`;\n}\n\nconst text = label("dark");', symbols: ['Theme', 'label', 'text'], topic: 'React composition', question: 'What is a good use for Context?', answer: 'A broadly needed stable value', recap: ['Context avoids passing a value through many layers.', 'Keep providers focused.', 'Do not put every changing value in one context.'] }),
  expandSeed({ id: 'react-reducer', title: 'Reducers for Complex State', moduleId: 'react-composition', description: 'A reducer gathers related state transitions in one function. Actions describe what happened, while the reducer decides the next state.', code: 'type State = { count: number };\ntype Action = { type: "increment" };\n\nfunction reducer(state: State, action: Action): State {\n  return action.type === "increment" ? { count: state.count + 1 } : state;\n}\n\nconst next = reducer({ count: 0 }, { type: "increment" });', symbols: ['State', 'Action', 'reducer', 'next'], topic: 'React composition', question: 'What should a reducer return?', answer: 'The next state', recap: ['Actions describe events.', 'Reducers centralize related transitions.', 'Keep reducers pure and predictable.'] }),
  expandSeed({ id: 'react-derived-state', title: 'Deriving Values During Render', moduleId: 'react-composition', description: 'If a value can be calculated from props or state, calculate it during render. Storing a duplicate introduces a second value that can fall out of sync.', code: 'type CartItem = { price: number; quantity: number };\n\nfunction total(items: CartItem[]) {\n  return items.reduce((sum, item) => sum + item.price * item.quantity, 0);\n}\n\nconst amount = total([{ price: 12, quantity: 2 }]);', symbols: ['CartItem', 'total', 'amount'], topic: 'React composition', question: 'Where should a value derived from state be calculated?', answer: 'During render', recap: ['Derive values when possible.', 'Avoid duplicated state.', 'Use an event only when user intent changes stored data.'] }),
  expandSeed({ id: 'react-memo', title: 'Memoizing Expensive Work', moduleId: 'react-performance', description: 'Memoization is a targeted optimization for calculations that are noticeably expensive. First keep renders pure and measure where the actual cost lives.', code: 'function expensiveTotal(values: number[]) {\n  return values.reduce((sum, value) => sum + value, 0);\n}\n\nconst total = expensiveTotal([2, 4, 8]);\nconsole.log(total);', symbols: ['expensiveTotal', 'total'], topic: 'React performance', question: 'When should you add memoization?', answer: 'After finding a meaningful performance cost', recap: ['Measure before optimizing.', 'Memoization caches a calculation.', 'Keep inputs and outputs predictable.'] }),
  expandSeed({ id: 'react-callbacks', title: 'Stable Callbacks', moduleId: 'react-performance', description: 'A callback changes identity when it is created again. Stabilize one only when a memoized child or Hook contract needs that stable reference.', code: 'type Action = () => string;\n\nconst save: Action = () => "saved";\nconst result = save();\nconsole.log(result);', symbols: ['Action', 'save', 'result'], topic: 'React performance', question: 'Why might a callback need a stable reference?', answer: 'A memoized consumer depends on its identity', recap: ['Functions are values too.', 'Stable callbacks are an optimization.', 'Do not add them by default.'] }),
  expandSeed({ id: 'react-transitions', title: 'Transitions and Responsive UI', moduleId: 'react-performance', description: 'A transition marks a state update as non-urgent so typing and direct feedback can remain responsive while a larger view catches up.', code: 'type Search = { term: string; pending: boolean };\n\nfunction beginSearch(term: string): Search {\n  return { term, pending: true };\n}\n\nconst search = beginSearch("react");', symbols: ['Search', 'beginSearch', 'search'], topic: 'React performance', question: 'What kind of update suits a transition?', answer: 'A non-urgent view update', recap: ['Urgent input should stay responsive.', 'Transitions communicate priority.', 'Use them around noticeable work.'] }),
  expandSeed({ id: 'react-accessibility', title: 'Accessible Interactive UI', moduleId: 'react-performance', description: 'Use native elements for their native jobs, then verify keyboard focus, visible labels, and feedback. Accessibility is part of a component contract.', code: 'type Button = { label: string; disabled: boolean };\n\nfunction canSubmit(button: Button) {\n  return !button.disabled && button.label.length > 0;\n}\n\nconst ready = canSubmit({ label: "Save", disabled: false });', symbols: ['Button', 'canSubmit', 'ready'], topic: 'React performance', question: 'What is the first choice for a clickable action?', answer: 'A native button element', recap: ['Prefer semantic HTML.', 'Every control needs a usable name.', 'Test keyboard and focus behavior.'] }),
  expandSeed({ id: 'react-form-validation', title: 'Form Validation', moduleId: 'react-practice', description: 'Validate the data model at the moment it matters, then communicate errors close to the field. A valid form is an explicit state, not a guess.', code: 'type Email = { value: string };\n\nfunction isValidEmail(email: Email) {\n  return email.value.includes("@");\n}\n\nconst valid = isValidEmail({ value: "hello@underco.de" });', symbols: ['Email', 'isValidEmail', 'valid'], topic: 'React practice', question: 'Where should an input error be shown?', answer: 'Close to the field it describes', recap: ['Validate user input deliberately.', 'Connect errors to their fields.', 'Keep submission state explicit.'] }),
  expandSeed({ id: 'react-request-states', title: 'Request States in React', moduleId: 'react-practice', description: 'A request can be idle, loading, successful, empty, or failed. Model those states clearly so the interface never leaves people guessing.', code: 'type Request = "idle" | "loading" | "success" | "error";\n\nfunction message(state: Request) {\n  return state === "loading" ? "Loading…" : "Ready";\n}\n\nconst text = message("loading");', symbols: ['Request', 'message', 'text'], topic: 'React practice', question: 'Which state should a request UI handle besides success?', answer: 'Loading and error states', recap: ['Requests have a lifecycle.', 'Plan empty results too.', 'Keep retry and recovery visible.'] }),
  expandSeed({ id: 'react-error-boundaries', title: 'Recovering From Render Errors', moduleId: 'react-practice', description: 'An Error Boundary gives a failed part of the interface a contained fallback. Pair it with a useful recovery action and enough context for debugging.', code: 'type Result<T> = { value?: T; error?: string };\n\nfunction fallback(result: Result<string>) {\n  return result.error ?? result.value ?? "Try again";\n}\n\nconst text = fallback({ error: "Could not load profile" });', symbols: ['Result', 'fallback', 'text'], topic: 'React practice', question: 'What should an error boundary provide?', answer: 'A contained fallback UI', recap: ['Contain failures when possible.', 'Give people a recovery path.', 'Log enough context to diagnose errors.'] }),
  expandSeed({ id: 'react-testing-behavior', title: 'Testing User Behavior', moduleId: 'react-practice', description: 'A useful component test checks what a person can see and do: render a state, interact, and observe the result. This protects behavior through refactors.', code: 'type TestCase = { name: string; expected: string };\n\nconst test: TestCase = { name: "submits form", expected: "success message" };\nconsole.log(test.expected);', symbols: ['TestCase', 'test'], topic: 'React practice', question: 'What should a component test focus on?', answer: 'Observable user behavior', recap: ['Test behavior over implementation details.', 'Cover important states.', 'Keep tests readable as product documentation.'] }),
  expandSeed({ id: 'react-feature-architecture', title: 'Organizing a React Feature', moduleId: 'react-practice', description: 'Group a feature around the work it owns: UI, stateful logic, data boundary, and tests. The folder should help a new reader find the next question quickly.', code: 'type Feature = { name: string; files: string[] };\n\nconst profile: Feature = { name: "profile", files: ["ProfileCard", "useProfile"] };\nconsole.log(profile.files);', symbols: ['Feature', 'profile'], topic: 'React practice', question: 'What should guide a feature folder?', answer: 'The responsibility the feature owns', recap: ['Organize around product responsibilities.', 'Keep public boundaries small.', 'Let related code live together.'] }),
  expandSeed({ id: 'react-preserving-state', title: 'Preserving and Resetting State', moduleId: 'react-composition', description: 'React preserves state for a component in the same position in the tree. Change a key when a new identity should begin with fresh state.', code: 'type Editor = { documentId: string; draft: string };\n\nfunction editorKey(editor: Editor) {\n  return `editor:${editor.documentId}`;\n}\n\nconst key = editorKey({ documentId: "lesson-1", draft: "" });', symbols: ['Editor', 'editorKey', 'key'], topic: 'React composition', question: 'What can intentionally reset a component’s state?', answer: 'Changing its key', recap: ['State belongs to a tree position.', 'Keys establish component identity.', 'Reset only when a new identity is intended.'] }),
  expandSeed({ id: 'react-virtualized-lists', title: 'Rendering Long Lists Responsibly', moduleId: 'react-performance', description: 'A very long list can make interaction slow because the browser must create and update many nodes. Virtualize only when the visible window is a small part of the full collection.', code: 'type Window = { start: number; end: number };\n\nfunction visible<T>(items: T[], window: Window) {\n  return items.slice(window.start, window.end);\n}\n\nconst rows = visible(["a", "b", "c", "d"], { start: 1, end: 3 });', symbols: ['Window', 'visible', 'rows'], topic: 'React performance', question: 'What does list virtualization render?', answer: 'The items currently visible in the viewport', recap: ['Measure list cost first.', 'Render the visible window when needed.', 'Keep keyboard navigation and semantics intact.'] }),
]

const nextExpansionSeeds: Seed[] = [
  expandSeed({ id: 'next-link-navigation', title: 'Navigation with Link', moduleId: 'next-routing', description: 'Use Link for in-app navigation so Next.js can preserve the application experience and prefetch likely destinations when appropriate.', code: 'function lessonHref(course: string, lesson: string) {\n  return `/learn/${course}/${lesson}`;\n}\n\nconst href = lessonHref("react", "state");', symbols: ['lessonHref', 'href'], topic: 'Next.js routing', question: 'Which component should handle an in-app route change?', answer: 'Link', recap: ['Use Link for internal navigation.', 'Write route paths deliberately.', 'Keep navigation labels descriptive.'] }),
  expandSeed({ id: 'next-route-groups', title: 'Route Groups and Organization', moduleId: 'next-routing', description: 'A route group organizes related folders without adding a URL segment. It is useful when sections need separate layouts or ownership while keeping clean URLs.', code: 'const folder = "(marketing)";\nconst visibleSegment = folder.startsWith("(") ? "" : folder;\nconsole.log(visibleSegment);', symbols: ['folder', 'visibleSegment'], topic: 'Next.js routing', question: 'Does a route group appear in the URL?', answer: 'No', recap: ['Route groups organize files.', 'They do not change the URL.', 'Use them for layout and ownership boundaries.'] }),
  expandSeed({ id: 'next-not-found', title: 'Not Found States', moduleId: 'next-routing', description: 'Call notFound when a requested resource does not exist or cannot be shown. A dedicated not-found UI makes an invalid route feel intentional and recoverable.', code: 'type Lesson = { title: string } | null;\n\nfunction isMissing(lesson: Lesson) {\n  return lesson === null;\n}\n\nconst missing = isMissing(null);', symbols: ['Lesson', 'isMissing', 'missing'], topic: 'Next.js routing', question: 'What should a route do for missing data?', answer: 'Render a deliberate not-found state', recap: ['Missing data is a normal route state.', 'Keep recovery navigation visible.', 'Do not render a broken empty page.'] }),
  expandSeed({ id: 'next-streaming-suspense', title: 'Streaming with Suspense', moduleId: 'next-rendering', description: 'Suspense lets a route reveal ready UI while a slower child is still loading. Put boundaries around meaningful sections so the fallback matches the work.', code: 'type Section = { ready: boolean };\n\nfunction status(section: Section) {\n  return section.ready ? "Content ready" : "Loading section";\n}\n\nconst text = status({ ready: false });', symbols: ['Section', 'status', 'text'], topic: 'Next.js rendering', question: 'What does a Suspense boundary allow?', answer: 'Part of a route to load independently', recap: ['Stream meaningful route sections.', 'Use useful loading fallbacks.', 'Do not hide the whole page for one slow detail.'] }),
  expandSeed({ id: 'next-caching-revalidation', title: 'Caching and Revalidation', moduleId: 'next-rendering', description: 'Choose freshness based on the data people need, then set a clear cache and revalidation strategy. Caching is a product decision as much as a performance one.', code: 'type CacheRule = { seconds: number };\n\nfunction isFresh(rule: CacheRule, age: number) {\n  return age < rule.seconds;\n}\n\nconst fresh = isFresh({ seconds: 60 }, 24);', symbols: ['CacheRule', 'isFresh', 'fresh'], topic: 'Next.js rendering', question: 'What should determine a revalidation window?', answer: 'How fresh the user needs the data to be', recap: ['Decide data freshness intentionally.', 'Cache keys should reflect the request.', 'Revalidate after meaningful changes.'] }),
  expandSeed({ id: 'next-server-actions', title: 'Server Actions', moduleId: 'next-rendering', description: 'Server Actions handle a form mutation close to the route that owns it. Treat their input as untrusted and return a clear success or error state.', code: 'type Input = { title: string };\n\nfunction normalize(input: Input) {\n  return { title: input.title.trim() };\n}\n\nconst data = normalize({ title: " New lesson " });', symbols: ['Input', 'normalize', 'data'], topic: 'Next.js rendering', question: 'Where should Server Action input be validated?', answer: 'On the server', recap: ['Server Actions own server mutations.', 'Validate every input.', 'Return a state the form can present.'] }),
  expandSeed({ id: 'next-loading-ui', title: 'Loading UI Files', moduleId: 'next-experience', description: 'A loading file supplies an immediate route-level fallback. Make it resemble the incoming content so people understand what is on its way.', code: 'type Loading = { label: string };\n\nconst loading: Loading = { label: "Loading lessons…" };\nconsole.log(loading.label);', symbols: ['Loading', 'loading'], topic: 'Next.js experience', question: 'What should a loading UI communicate?', answer: 'What content is currently being prepared', recap: ['Loading is part of the route design.', 'Match the layout where possible.', 'Keep it quick and informative.'] }),
  expandSeed({ id: 'next-error-ui', title: 'Route Error Recovery', moduleId: 'next-experience', description: 'An error file contains a failure within its route segment and can offer a retry. Write the fallback for the person seeing it, not only the developer reading logs.', code: 'type Failure = { message: string; retryable: boolean };\n\nfunction action(failure: Failure) {\n  return failure.retryable ? "Try again" : "Return home";\n}\n\nconst nextStep = action({ message: "Unavailable", retryable: true });', symbols: ['Failure', 'action', 'nextStep'], topic: 'Next.js experience', question: 'What is a useful route error fallback?', answer: 'A clear explanation with a recovery action', recap: ['Contain errors to a route segment.', 'Offer retry when appropriate.', 'Keep technical details out of the main message.'] }),
  expandSeed({ id: 'next-fonts-images', title: 'Fonts and Images', moduleId: 'next-experience', description: 'Load fonts and images with their display behavior in mind. Reserve image space and avoid shifting content after a person has started reading.', code: 'type ImageSize = { width: number; height: number };\n\nfunction ratio(size: ImageSize) {\n  return size.width / size.height;\n}\n\nconst aspect = ratio({ width: 1200, height: 800 });', symbols: ['ImageSize', 'ratio', 'aspect'], topic: 'Next.js experience', question: 'Why should an image have known dimensions?', answer: 'To reserve space and avoid layout shift', recap: ['Reserve image space.', 'Load fonts deliberately.', 'Protect reading and interaction stability.'] }),
  expandSeed({ id: 'next-forms-validation', title: 'Forms and Server Validation', moduleId: 'next-mutations', description: 'A form can provide immediate client hints, but the server remains the authority for validation. Return field level feedback in a shape the UI can render.', code: 'type Signup = { email: string };\n\nfunction validate(input: Signup) {\n  return input.email.includes("@") ? null : "Enter a valid email";\n}\n\nconst error = validate({ email: "hello" });', symbols: ['Signup', 'validate', 'error'], topic: 'Next.js mutations', question: 'Where must form data be validated?', answer: 'On the server', recap: ['Treat every request as untrusted.', 'Return useful field feedback.', 'Keep success and pending states visible.'] }),
  expandSeed({ id: 'next-optimistic-ui', title: 'Optimistic UI', moduleId: 'next-mutations', description: 'Optimistic UI shows the expected result before the server confirms it. Use it for actions that feel safe, then reconcile or recover when the request fails.', code: 'type Todo = { title: string; pending: boolean };\n\nfunction optimistic(title: string): Todo {\n  return { title, pending: true };\n}\n\nconst todo = optimistic("Ship lesson");', symbols: ['Todo', 'optimistic', 'todo'], topic: 'Next.js mutations', question: 'What must optimistic UI plan for?', answer: 'A failed server request', recap: ['Show the expected state quickly.', 'Mark pending work clearly.', 'Recover when the server disagrees.'] }),
  expandSeed({ id: 'next-revalidate-path', title: 'Refreshing Changed Data', moduleId: 'next-mutations', description: 'After a successful mutation, revalidate the route or tag that depends on the changed data. This keeps cached views aligned with the source of truth.', code: 'type Change = { path: string };\n\nfunction refreshTarget(change: Change) {\n  return `refresh:${change.path}`;\n}\n\nconst target = refreshTarget({ path: "/learn" });', symbols: ['Change', 'refreshTarget', 'target'], topic: 'Next.js mutations', question: 'When should a cached route be revalidated?', answer: 'After data it depends on changes', recap: ['Mutations affect cached views.', 'Refresh the smallest relevant area.', 'Keep invalidation near the write.'] }),
  expandSeed({ id: 'next-auth-boundaries', title: 'Authorization Boundaries', moduleId: 'next-mutations', description: 'Authentication identifies a person; authorization decides whether that person may perform this action. Enforce both rules on the server for every sensitive mutation.', code: 'type Actor = { role: "reader" | "editor" };\n\nfunction canPublish(actor: Actor) {\n  return actor.role === "editor";\n}\n\nconst allowed = canPublish({ role: "editor" });', symbols: ['Actor', 'canPublish', 'allowed'], topic: 'Next.js mutations', question: 'Where must authorization be enforced?', answer: 'On the server', recap: ['Authentication and authorization differ.', 'Check permission per action.', 'Never trust a browser-only check.'] }),
  expandSeed({ id: 'next-route-handlers', title: 'Designing Route Handlers', moduleId: 'next-mutations', description: 'A Route Handler is an HTTP boundary. Parse input, validate it, authorize the caller, do one focused job, and return an explicit response.', code: 'type RequestBody = { title?: string };\n\nfunction hasTitle(body: RequestBody) {\n  return typeof body.title === "string" && body.title.length > 0;\n}\n\nconst valid = hasTitle({ title: "New route" });', symbols: ['RequestBody', 'hasTitle', 'valid'], topic: 'Next.js mutations', question: 'What should a Route Handler do before business work?', answer: 'Validate input and authorize the caller', recap: ['HTTP boundaries need validation.', 'Return clear status and data.', 'Keep each handler focused.'] }),
  expandSeed({ id: 'next-code-splitting', title: 'Code Splitting by Route', moduleId: 'next-optimization', description: 'Routes naturally split application code, and dynamic imports can defer an optional heavy feature. Load more JavaScript only when the experience needs it.', code: 'type Feature = { requested: boolean };\n\nfunction shouldLoad(feature: Feature) {\n  return feature.requested;\n}\n\nconst loadEditor = shouldLoad({ requested: true });', symbols: ['Feature', 'shouldLoad', 'loadEditor'], topic: 'Next.js optimization', question: 'When is a dynamic import useful?', answer: 'When a feature is optional or costly to load up front', recap: ['Routes split code naturally.', 'Defer optional heavy features.', 'Optimize based on evidence.'] }),
  expandSeed({ id: 'next-client-boundaries', title: 'Keeping Client Boundaries Small', moduleId: 'next-optimization', description: 'Move interactivity into a focused Client Component and keep surrounding layout and data work on the server. This reduces browser JavaScript without losing usability.', code: 'type Boundary = { interactive: boolean; size: "small" | "large" };\n\nconst boundary: Boundary = { interactive: true, size: "small" };\nconsole.log(boundary);', symbols: ['Boundary', 'boundary'], topic: 'Next.js optimization', question: 'Where should a client boundary usually sit?', answer: 'Around the smallest interactive part', recap: ['Server is the default.', 'Isolate browser-only behavior.', 'Keep data and layout outside when possible.'] }),
  expandSeed({ id: 'next-seo-metadata', title: 'Route Metadata and Sharing', moduleId: 'next-optimization', description: 'Write page titles and descriptions for the route’s actual content. Metadata should help search and sharing previews set accurate expectations before a visit.', code: 'type Metadata = { title: string; description: string };\n\nconst metadata: Metadata = { title: "React lessons", description: "Learn React one idea at a time." };\nconsole.log(metadata.title);', symbols: ['Metadata', 'metadata'], topic: 'Next.js optimization', question: 'What should route metadata describe?', answer: 'The specific content of that route', recap: ['Metadata belongs with its route.', 'Write accurate titles and descriptions.', 'Keep sharing previews intentional.'] }),
  expandSeed({ id: 'next-web-vitals', title: 'Reading Web Vitals', moduleId: 'next-optimization', description: 'Web Vitals describe loading, visual stability, and interaction responsiveness. Use measurements to locate a bottleneck before changing route architecture.', code: 'type Metric = { name: string; value: number };\n\nfunction report(metric: Metric) {\n  return `${metric.name}: ${metric.value}`;\n}\n\nconst line = report({ name: "LCP", value: 1800 });', symbols: ['Metric', 'report', 'line'], topic: 'Next.js optimization', question: 'What should guide a performance change?', answer: 'Measured user-facing behavior', recap: ['Measure real experience.', 'Find the limiting route or asset.', 'Verify improvements after a change.'] }),
  expandSeed({ id: 'next-environment-variables', title: 'Environment Variables', moduleId: 'next-production', description: 'Environment variables separate deployment configuration from source code. Only explicitly public values belong in browser code; secrets must remain server-only.', code: 'type Config = { apiUrl: string };\n\nconst config: Config = { apiUrl: "https://api.example.com" };\nconsole.log(config.apiUrl);', symbols: ['Config', 'config'], topic: 'Next.js production', question: 'Where should a secret environment variable be used?', answer: 'Only on the server', recap: ['Keep secrets out of browser bundles.', 'Document required configuration.', 'Use separate values per environment.'] }),
  expandSeed({ id: 'next-deployment-checklist', title: 'Preparing a Production Build', moduleId: 'next-production', description: 'A production release needs a clean build, expected environment values, route checks, and error visibility. Treat deployment as a repeatable product workflow.', code: 'type Release = { built: boolean; configured: boolean };\n\nfunction ready(release: Release) {\n  return release.built && release.configured;\n}\n\nconst ship = ready({ built: true, configured: true });', symbols: ['Release', 'ready', 'ship'], topic: 'Next.js production', question: 'What should happen before deployment?', answer: 'Build and verify the application in its target configuration', recap: ['Build before release.', 'Check critical routes.', 'Verify runtime configuration.'] }),
  expandSeed({ id: 'next-observability', title: 'Observing Route Failures', moduleId: 'next-production', description: 'Production logs and error reports should answer what failed, where it happened, and how often. Capture context safely without putting private user data into logs.', code: 'type Event = { route: string; outcome: "success" | "error" };\n\nconst event: Event = { route: "/learn/react", outcome: "success" };\nconsole.log(event);', symbols: ['Event', 'event'], topic: 'Next.js production', question: 'What should an error report include?', answer: 'Useful route and failure context without private data', recap: ['Observe important failures.', 'Protect user data in logs.', 'Use evidence to prioritize fixes.'] }),
  expandSeed({ id: 'next-security-headers', title: 'Protecting the Request Boundary', moduleId: 'next-production', description: 'Security belongs at every request boundary: validate input, use secure cookies, set suitable headers, and avoid exposing server internals in errors.', code: 'type Request = { origin: string };\n\nfunction trusted(request: Request) {\n  return request.origin === "https://undercode.dev";\n}\n\nconst accepted = trusted({ origin: "https://undercode.dev" });', symbols: ['Request', 'trusted', 'accepted'], topic: 'Next.js production', question: 'What should happen to untrusted request input?', answer: 'Validate it before using it', recap: ['Every request is untrusted input.', 'Keep sensitive work server-side.', 'Return safe error messages.'] }),
  expandSeed({ id: 'next-full-route-review', title: 'Reviewing a Complete Route', moduleId: 'next-production', description: 'A complete route connects navigation, data, loading, empty, error, success, metadata, and accessibility. Review the whole journey before calling it done.', code: 'type RouteReview = { loading: boolean; empty: boolean; error: boolean; success: boolean };\n\nconst review: RouteReview = { loading: true, empty: true, error: true, success: true };\nconsole.log(review);', symbols: ['RouteReview', 'review'], topic: 'Next.js production', question: 'Which route state is easy to forget but important to design?', answer: 'Empty and error states', recap: ['Review the entire route lifecycle.', 'Check loading, empty, error, and success.', 'Verify keyboard and sharing behavior too.'] }),
  expandSeed({ id: 'next-bundle-analysis', title: 'Reviewing What Reaches the Browser', moduleId: 'next-optimization', description: 'A bundle review shows which client dependencies reach a route. Use it to remove unused work and move server-safe logic out of browser boundaries.', code: 'type Bundle = { route: string; kilobytes: number };\n\nfunction isLarge(bundle: Bundle) {\n  return bundle.kilobytes > 200;\n}\n\nconst review = isLarge({ route: "/learn", kilobytes: 180 });', symbols: ['Bundle', 'isLarge', 'review'], topic: 'Next.js optimization', question: 'What does bundle analysis help you find?', answer: 'Client code that is unnecessarily large or unused', recap: ['Inspect what each route sends.', 'Move eligible logic to the server.', 'Remove dependencies with no user benefit.'] }),
]

export const frameworkModules: CourseModule[] = [
  { id: 'react-foundations', courseId: 'react', number: '01', title: 'React Foundations', description: 'Build a clear model of components, JSX, and props.' },
  { id: 'react-state', courseId: 'react', number: '02', title: 'State & Interaction', description: 'Model changing UI, events, and lists.' },
  { id: 'react-effects', courseId: 'react', number: '03', title: 'Thinking Beyond Render', description: 'Connect external systems, reusable logic, and composition.' },
  { id: 'react-composition', courseId: 'react', number: '04', title: 'Sharing & Structuring State', description: 'Coordinate related components, shared values, and complex transitions.' },
  { id: 'react-performance', courseId: 'react', number: '05', title: 'Responsive, Accessible UI', description: 'Keep interactions fast, focused, and usable for everyone.' },
  { id: 'react-practice', courseId: 'react', number: '06', title: 'Reliable React Features', description: 'Handle forms, requests, recovery, testing, and feature boundaries.' },
  { id: 'next-routing', courseId: 'nextjs', number: '01', title: 'Routes & Layouts', description: 'Use the App Router to shape navigation and nested UI.' },
  { id: 'next-rendering', courseId: 'nextjs', number: '02', title: 'Rendering & Data', description: 'Choose server and client boundaries, then fetch data deliberately.' },
  { id: 'next-experience', courseId: 'nextjs', number: '03', title: 'Reliable Route Experiences', description: 'Design loading, error, metadata, and HTTP route behavior.' },
  { id: 'next-mutations', courseId: 'nextjs', number: '04', title: 'Forms & Server Mutations', description: 'Validate writes, refresh changed data, and enforce server boundaries.' },
  { id: 'next-optimization', courseId: 'nextjs', number: '05', title: 'Fast, Discoverable Routes', description: 'Shape bundle size, client boundaries, metadata, and user-facing performance.' },
  { id: 'next-production', courseId: 'nextjs', number: '06', title: 'Production-Ready Applications', description: 'Configure, observe, protect, and review complete route experiences.' },
]
export const frameworkLessons = [...makeLessons('react', [...reactSeeds, ...reactExpansionSeeds]), ...makeLessons('nextjs', [...nextSeeds, ...nextExpansionSeeds])]
export const frameworkConcepts: Concept[] = frameworkLessons.map((lesson) => ({ id: `${lesson.courseId}-${lesson.id}`, courseId: lesson.courseId, title: lesson.title, category: lesson.challenge.topic, description: lesson.description, code: lesson.code, lessonId: lesson.id, visual: lesson.visual }))
