/** Small experiments connect each core TypeScript lesson to its own contract. */
export const typeScriptPractice: Record<string, string> = {
  'why-typescript': 'Pass "19.5" to formatPrice and read the diagnostic. Restore a number, then explain what the checker can catch before execution.',
  'javascript-vs-typescript': 'Try add(4, "2") and compare the diagnostic with JavaScript concatenation. Restore two numbers and inspect total.',
  'your-first-type': 'Change the annotated value to text, inspect the error, and restore a valid value. Explain what the annotation promises.',
  'primitive-types': 'Assign a string to lessons, then null to title. Restore the values and explain why subtitle permits null.',
  'type-inference': 'Assign text to score and inspect the error. Compare mode, settings.mode, and fixedSettings.mode in the type inspector.',
  arrays: 'Push another string into labels, then try a number. Annotate labels with string[] and Array<string> and explain the shared contract.',
  objects: 'Remove a required property from learner, inspect the diagnostic, then restore it. Change a value while keeping the declared object shape.',
  'union-types': 'Call displayId with a number and a string. Move toUpperCase outside the guard and explain the diagnostic.',
  parameters: 'Try a numeric and a string argument. Restore the valid call, then explain how the parameter annotation protects the function boundary.',
  'return-types': 'Change remaining to return a string with toString(), inspect the error, and restore the numeric result. Compare the type of count.',
  'optional-parameters': 'Call greet with no nickname, an empty nickname, and undefined. Compare ?? with || and explain the difference.',
  'function-types': 'Change formatPercent to return a number instead of text. Read the diagnostic, then restore a string and try a different formatter.',
  'type-aliases': 'Change LessonId from string to "interfaces" | "unions". Try a different id in nextLesson, then add it deliberately to the alias.',
  interfaces: 'Change course.title, then try changing course.id. Explain why readonly affects type checking without freezing the object.',
  'optional-properties': 'Omit the optional field, supply a value, and try undefined. Compare omission with explicit undefined under exact optional property checking.',
  'extending-interfaces': 'Remove an inherited field from the value, inspect the error, and restore it. Name the fields required by the extended interface.',
  'literal-types': 'Try a status outside the union, then add a deliberate new variant. Compare a normal object with an as const configuration.',
  narrowing: 'Try both success and failure variants. Add a new variant and explain which branch needs to handle it.',
  keyof: 'Change key from "title" to "minutes" and inspect value. Try a misspelled key and explain how keyof rejects it.',
  typeof: 'Change defaults.fontSize to a string and inspect the derived Settings type. Restore it, then compare runtime typeof with the type query.',
  'utility-types': 'Create an update containing just one property, then try an unrelated property. Explain why Partial changes the contract but does not apply an update.',
  'why-generics': 'Pass a number and an object to identity. Inspect each result and explain how its type stays connected to the input.',
  'generic-functions': 'Try first with a nonempty list and an empty one. Handle undefined before using the returned value.',
  'generic-constraints': 'Remove id from the value passed to withLabel. Restore it, then try a missing key in getProperty and explain each diagnostic.',
  'generic-interfaces': 'Create a Page<number> with numeric items. Try a string item and inspect the diagnostic, then compare it with Page<Lesson>.',
  'typing-api-responses': 'Change the JSON to null, a missing name, and a string id. Compare the guard results with a type assertion that performs no checks.',
  'async-functions': 'Make loadLesson throw an Error and follow the recovery path. Restore success, then inspect the Promise and fulfilled-value types.',
  'practical-data-models': 'Call describe for idle, loading, ready, and error. Try a ready state without data and explain the rejected shape.',
  'react-props': 'Change the callback parameter type and inspect the mismatch. Restore it, then omit the optional variant and explain the fallback.',
  'final-challenge': 'Try an empty list, all-ready lessons, and all-complete lessons. Check that total and completed match each input without weakening the types.',
}
