import { foundation } from './model'

export const thinking = foundation({ id: 'logic', title: 'Logic & Problem Solving', eyebrow: 'Start with a way of thinking', description: 'Turn everyday problems into clear steps, decisions, and repeatable instructions.', prerequisite: 'No coding experience' }, [
  { id: 'logic-instructions', title: 'Instructions and Algorithms', idea: 'An algorithm is a sequence of precise steps that takes an input and produces a result.', explain: 'Imagine calculating the cost of a basket. Read the price, read the quantity, multiply them, then display the total. Order matters: displaying the total before calculating it does not solve the problem. JavaScript below is a way to write these instructions; focus on the steps first. Read const price = 12 as “name the value 12 price.” The = assigns a value, * multiplies, and console.log displays a result. A semicolon ends an instruction. Read from top to bottom, predict, then run; no JavaScript experience is needed.', code: 'const price = 12;\nconst quantity = 3;\nconst total = price * quantity;\nconsole.log(total);', practice: 'Predict the total. Run the code, then change quantity to 5 and predict again.', question: 'What is the output when price is 12 and quantity is 3?', options: ['36', '15', '123'], answer: '36', reason: 'Multiplication combines the price of one item with the number of items: 12 × 3 = 36.', hint: 'The * symbol means multiply.', flow: ['Price + quantity', 'Multiply', 'Basket total'], recap: ['An algorithm describes precise steps.', 'Predict a result before running an example.'], visual: {
    title: 'Turn two inputs into a total',
    description: 'Adjust the values, then follow how each input reaches the result.',
    nodes: [
      { id: 'price', label: 'Price', detail: 'This is the cost of one item.', tone: 'value' },
      { id: 'quantity', label: 'Quantity', detail: 'This is how many items are being bought.', tone: 'value' },
      { id: 'multiply', label: 'Multiply', symbol: '×', detail: 'The multiplication step combines price and quantity.' },
      { id: 'total', label: 'Basket total', detail: 'This is the result after both inputs have been multiplied.', tone: 'value' },
    ],
    edges: [
      { from: 'price', to: 'multiply', label: 'price', detail: 'The price flows into the multiplication step.' },
      { from: 'quantity', to: 'multiply', label: 'quantity', detail: 'The quantity becomes the second input for multiplication.' },
      { from: 'multiply', to: 'total', label: 'result', detail: 'Multiplication produces the basket total.' },
    ],
    simulation: { kind: 'multiply', inputs: [{ nodeId: 'price', initial: 12, min: 1, max: 50, step: 1 }, { nodeId: 'quantity', initial: 3, min: 1, max: 12, step: 1 }], outputNodeId: 'total' },
  } },
  { id: 'logic-decisions', title: 'Decisions and Conditions', idea: 'A condition lets a program choose a different action based on what is true.', explain: 'A shop might offer free delivery when the basket reaches 50. The comparison total >= 50 produces true or false. Only the matching branch runs. Test values below, exactly at, and above the boundary to understand the rule.', code: 'const total = 50;\nif (total >= 50) {\n  console.log("Free delivery");\n} else {\n  console.log("Delivery costs 5");\n}', practice: 'Try totals of 49, 50, and 51. Explain why 50 receives free delivery.', question: 'Which total receives free delivery?', options: ['50', '49', '0'], answer: '50', reason: 'The >= comparison includes the boundary: a total equal to 50 qualifies.', hint: 'Read >= as greater than or equal to.', flow: ['Basket total', 'At least 50?', 'Choose a delivery cost'], recap: ['Conditions produce a boolean decision.', 'Check the value exactly on a boundary.'] },
  { id: 'logic-repetition', title: 'Repeating a Small Step', idea: 'A loop repeats an instruction while a rule says there is still work to do.', explain: 'The loop starts with item = 1, checks item <= 3, prints one label, then adds one to item. At 4 the condition is false, so the loop stops. A useful loop always has a way to finish.', code: 'for (let item = 1; item <= 3; item++) {\n  console.log("Pack item " + item);\n}', practice: 'Change the last item to 5. Count the output lines and compare with your prediction.', question: 'How many labels does the original loop print?', options: ['3', '4', 'Forever'], answer: '3', reason: 'It prints for 1, 2, and 3. The condition rejects 4.', hint: 'Write down each allowed value of item.', flow: ['Start at 1', 'Print and add 1', 'Stop after 3'], recap: ['Loops make repeated work explicit.', 'A stopping condition prevents endless work.'] },
  { id: 'logic-decomposition', title: 'Break a Problem into Parts', idea: 'A big task becomes easier when each smaller part has one clear job.', explain: 'A checkout can calculate a subtotal separately from delivery. Here basketTotal receives prices and returns a number. The function keyword gives this group of steps a name; prices is the input, and return sends the result back to its caller. Square brackets hold an ordered list of values: [10, 15, 5] has three prices, while [] is empty. The for...of loop reads one price at a time; total += price means total = total + price. Keeping the calculation separate lets you try different baskets without changing the other checkout steps.', code: 'function basketTotal(prices) {\n  let total = 0;\n  for (const price of prices) total += price;\n  return total;\n}\nconsole.log(basketTotal([10, 15, 5]));\nconsole.log(basketTotal([]));', practice: 'Predict both outputs. Try a basket with one item, then explain why an empty basket returns 0.', question: 'What is basketTotal responsible for?', options: ['Adding the supplied prices', 'Charging a bank card', 'Designing a checkout page'], answer: 'Adding the supplied prices', reason: 'Its input is a list of prices and its output is their sum. Other jobs belong in other parts.', hint: 'Look at what enters the function and what it returns.', flow: ['List of prices', 'Add one at a time', 'Return a total'], recap: ['Give each part one understandable job.', 'Try normal, empty, and boundary inputs.'] },
])

export const web = foundation({ id: 'web', title: 'Web & Developer Tools', eyebrow: 'Find your bearings', description: 'Understand browsers, files, developer tools, and the first steps of version control.', prerequisite: 'Basic problem solving' }, [
  { id: 'web-browser', title: 'How a Web Page Arrives', idea: 'A browser requests a resource from a server, then turns the response into a page.', explain: 'HTML supplies structure, CSS supplies presentation, and JavaScript supplies behavior. A URL identifies a resource. The server responds to an HTTP request; the browser parses the returned HTML and requests any linked resources it needs. A local file can also open in a browser without being published.', code: 'Browser → GET /index.html → Server\nBrowser ← HTML response ← Server\nHTML → document structure\nCSS → layout and appearance\nJavaScript → interaction', language: 'text', lab: 'read', practice: 'Open a website and name one example of structure, presentation, and interaction on the page.', question: 'Which technology describes a page’s content structure?', options: ['HTML', 'CSS', 'A Git commit'], answer: 'HTML', reason: 'HTML describes elements and meaning; CSS controls their appearance.', hint: 'Separate what the content is from how it looks.', flow: ['Request', 'HTML response', 'Rendered page'], recap: ['The browser renders resources it receives.', 'HTML, CSS, and JavaScript have different roles.'] },
  { id: 'web-files', title: 'Files, Folders, and Paths', idea: 'A small website starts as related files with addresses relative to one another.', explain: 'Keep index.html, styles.css, and app.js in a project folder. A relative path such as ./styles.css starts next to the current document. File names can be case sensitive on a host even if they seem interchangeable locally. Save an edit before reloading a local page.', code: 'my-site/\n  index.html\n  styles.css\n  app.js\n  images/\n    portrait.png\n\n<!-- inside index.html -->\n<link rel="stylesheet" href="./styles.css">', language: 'text', lab: 'read', practice: 'Create a folder and an index.html file locally, or use the browser labs in the next stage. Explain where ./images/portrait.png points.', question: 'Which path points to the stylesheet next to index.html?', options: ['./styles.css', './images/styles.css', 'portrait.png'], answer: './styles.css', reason: 'The ./ prefix refers to the current folder, where styles.css is stored.', hint: 'Trace the folder tree from index.html.', flow: ['Project folder', 'Relative path', 'Linked resource'], recap: ['Keep related files together.', 'Match paths and filename casing exactly.'] },
  { id: 'web-debugging', title: 'Inspect, Observe, Debug', idea: 'Debugging starts by comparing what you expected with what actually happened.', explain: 'The Elements panel shows the live document and applied styles. Console shows logged values and errors. Network shows requests and responses. Choose the panel that matches the symptom, change one thing, and observe again. A console error is a clue about a specific failure, not proof that the entire project is broken.', code: 'const price = "10";\nconsole.log(typeof price);\nconsole.log(price + 5);\nconsole.log(Number(price) + 5);', practice: 'Run the example and explain why the last two lines differ. In your browser, find the Console panel in developer tools.', question: 'Which tool helps investigate a request that failed to load?', options: ['Network panel', 'Font picker', 'Git log'], answer: 'Network panel', reason: 'Network shows whether a resource was requested and the status of the response.', hint: 'A request is communication between the browser and a resource.', flow: ['Unexpected result', 'Observe evidence', 'Change one cause'], recap: ['Inspect the evidence before guessing a fix.', 'Different developer tools answer different questions.'] },
  { id: 'web-version-control', title: 'Save Meaningful Versions', idea: 'Git records snapshots so you can understand how a project changed over time.', explain: 'Editing a file changes your working tree. Staging selects the changes for a snapshot; committing records that snapshot locally. Pushing sends commits to a remote repository and is a separate action. Always inspect the diff and exclude secrets before recording or sharing changes.', code: 'git status\ngit diff\n\n# A local snapshot, when you are ready:\ngit add index.html styles.css\ngit commit -m "feat: add profile page"', language: 'text', lab: 'read', practice: 'Describe the difference between saving a file, making a commit, and pushing. These commands are a reading example; this lesson does not run them.', question: 'Does creating a local commit automatically publish it to GitHub?', options: ['No, pushing is a separate step', 'Yes, always', 'Only for CSS files'], answer: 'No, pushing is a separate step', reason: 'A commit belongs to the local repository until it is sent to a remote.', hint: 'Local history and remote hosting are different places.', flow: ['Working changes', 'Selected snapshot', 'Local commit'], recap: ['Review changes before recording them.', 'A commit and a push are separate actions.'] },
])
